name: Pack and Deploy

on:
  push:
    branches:
      - main
      # TODO remove me before we merge the feature branch to main
      - feature/charm-cicd
  release:
    types:
      - published

concurrency:
    group: "deploy-${{ github.ref }}"
    cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    # https://github.com/canonical/webteam-devops
    # Uncomment after https://github.com/canonical/webteam-devops/issues/4 is resolved.
    # uses: canonical/webteam-devops/.github/workflows/deploy.yaml@main
    uses: ./.github/workflows/webteam-devops-deploy-fork.yml
    with:
      environment: ${{ github.event_name == 'release' && 'Production' || 'Staging' }}
      charm_name: ${{ vars.CHARM_NAME }}
      channel: ${{ vars.CHANNEL }}
      juju_controller_name: ${{ vars.JUJU_CONTROLLER_NAME }}
      juju_model_name: ${{ vars.JUJU_MODEL_NAME }}
    secrets:
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      # See https://canonical-charmcraft.readthedocs-hosted.com/en/stable/reference/commands/login/ to create a Charmhub token
      # Use `charmcraft login --export path/to/save-token-file` to create the token file.
      # Then, base64-encode it: `cat path/to/save-token-file | base64`
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
